### ISSUE TITLE
[Raid] UBRS - Rend Event Crashing Server

### ISSUE THREAD

**Issue by Santah62** [NoxGaming/TrinityCore#116] opened 2018-09-13 02:29 UTC
**Description:**

Shortly after killing Rend Blackhand the server crashes

**Comment by HelloKitty** [comment] 2018-09-14 21:37
Just as a note to anyone looking, UBRS will have a nearly full rewrite so this issue will be addressed but not directly.

**Comment by natnat201193** [comment] 2018-09-16 05:56
This is a server Freeze, not a crash. Tested This on local, once the fight is completed. it resets and starts again, then once you get to rend for the 2nd time. thats when the server freezes. cant get crash log because of this so would need debugging to find the cause. But as its gonna get rewrote i guess it doesnt matter. putting this here just for extra info.

**Comment by natnat201193** [comment] 2018-09-20 05:04
https://github.com/TrinityCore/TrinityCore/issues/22452

**Comment by Nyeriah** [comment] 2018-09-26 04:37
https://github.com/NoxGaming/TrinityCore/commit/af3449e06463b3425df2ce67195fa55492af4151

**Comment by whammyresilience** [comment] 2018-09-29 03:49
@Nyeriah The event is no longer causing any freezing or crashes but Lord Victor Nefarius still remains pathing back and forth like he does during the fight. The door to leave the room also does not open. I suspect there may be something stopping the event from continuing after Rend dies.

**Comment by natnat201193** [comment] 2018-09-29 03:51
As long as it doesnt crash or freeze for now. the entire fight is in need of alot of work. so those issues will be addressed eventually.

**Comment by whammyresilience** [comment] 2018-09-29 04:06
Ok, I'm going to close this for now then as the issue in the ticket is resolved.

**Closed by whammyresilience** 2018-09-29 04:06 UTC
Labels: Confirmed Bug, Major/High Priority, Mechanics, Raid
